apiVersion: v1
kind: ReplicationController
metadata:
  name: rehearsal-centos-6-package-list
spec:
  replicas: 1
  selector:
    app: rehearsal-centos-6-package-list
  template:
    metadata:
      name: rehearsal-centos-6-package-list
      labels:
        app: rehearsal-centos-6-package-list
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: rehearsal-centos-6-package-list
        image: arjunguha/rehearsal-centos-6-package-list
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: rehearsal-centos-6-package-list
spec:
  selector:
    app: rehearsal-centos-6-package-list
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rehearsal-ubuntu-trusty-package-list
spec:
  replicas: 1
  selector:
    app: rehearsal-ubuntu-trusty-package-list
  template:
    metadata:
      name: rehearsal-ubuntu-trusty-package-list
      labels:
        app: rehearsal-ubuntu-trusty-package-list
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: rehearsal-ubuntu-trusty-package-list
        image: arjunguha/rehearsal-ubuntu-trusty-package-list
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: rehearsal-ubuntu-trusty-package-list
spec:
  selector:
    app: rehearsal-ubuntu-trusty-package-list
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rehearsal-package-list
spec:
  replicas: 1
  selector:
    app: rehearsal-package-list
  template:
    metadata:
      name: rehearsal-package-list
      labels:
        app: rehearsal-package-list
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: rehearsal-package-list
        image: arjunguha/rehearsal-package-list
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: rehearsal-package-list
spec:
  selector:
    app: rehearsal-package-list
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rehearsal
spec:
  replicas: 1
  selector:
    app: rehearsal
  template:
    metadata:
      name: rehearsal
      labels:
        app: rehearsal
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: rehearsal
        image: arjunguha/rehearsal
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: rehearsal
spec:
  type: NodePort
  selector:
    app: rehearsal
  ports:
    - port: 8080
      nodePort: 30002
      targetPort: http